---
version: "3.9"
services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile.webui
    ports:
      - "3000:3000"
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    volumes:
      - "./data:/data:rw"
      - ".:/logs:rw"
    expose:
      - "8432"
    ports:
      - "8432:8432"
      - "8434-8700:8434-8700"
    environment:
      - DIPLOMACY_ADMIN_PASSWORD=tacobot
      - SERVER_PORT=8432
      - DAIDE_PORT_RANGE=8434:8700
