FROM python:3.7

ARG GIT_REPO=https://github.com/SHADE-AI/diplomacy.git
ARG GIT_BRANCH=development

# Install SHADE-AI's development version
RUN git clone -b ${GIT_BRANCH} ${GIT_REPO} /code/diplomacy
RUN pip install --upgrade /code/diplomacy

RUN mkdir -p /logs && touch /logs/diplomacy.server.log

ENV DAIDE_PORT_RANGE=8434:8600
ENV DIPLOMACY_ADMIN_PASSWORD=password
ENV SERVER_PORT=8432

CMD ["/bin/sh", "-c", "python -m diplomacy.server.run >> /logs/diplomacy_server_run.log 2>&1"]
