#!/usr/bin/env python3


locations={
    "ADR":"Adriatic Sea",
    "AEG":"Aegean Sea",
    "ALB":"Albania",
    "ANK":"Ankara",
    "APU":"Apulia",
    "ARM":"Armenia",
    "BAL":"Baltic Sea",
    "BAR":"Barents Sea",
    "BEL":"Belgium",
    "BER":"Berlin",
    "BLA":"Black Sea",
    "BOH":"Bohemia",
    "BRE":"Brest",
    "BUD":"Budapest",
    "BUL":"Bulgaria",
    "BUR":"Burgundy",
    "CLY":"Clyde",
    "CON":"Constantinople",
    "DEN":"Denmark",
    "EAS":"Eastern Mediterranean Sea",
    "ECH":"English Channel",
    "EDI":"Edinburgh",
    "FIN":"Finland",
    "GAL":"Galecia",
    "GAS":"Gascony",
    "GOB":"Gulf of Bothnia",
    "GOL":"Gulf of Lyons",
    "GRE":"Greece",
    "HEL":"Helgoland Bight",
    "HOL":"Holland",
    "ION":"Ionian Sea",
    "IRI":"Irish Sea",
    "KIE":"Kiel",
    "LON":"London",
    "LVN":"Livonia",
    "LVP":"Liverpool",
    "MAO":"Mid Atlantic Ocean",
    "MAR":"Marseilles",
    "MOS":"Moscow",
    "MUN":"Munich",
    "NAF":"North Africa",
    "NAO":"North Atlantic Ocean",
    "NAP":"Naples",
    "NTH":"North Sea",
    "NWG":"Norwegian Sea",
    "NWY":"Norway",
    "PAR":"Paris",
    "PIC":"Picardy",
    "PIE":"Piedmont",
    "POR":"Portugal",
    "PRU":"Prussia",
    "ROM":"Rome",
    "RUH":"Ruhr",
    "RUM":"Rumania",
    "SER":"Serbia",
    "SEV":"Sevastopol",
    "SIL":"Silesia",
    "SKA":"Skaggerack",
    "SMY":"Smyrna",
    "SPA":"Spain",
    "STP":"St Petersburg",
    "SWE":"Sweden",
    "SYR":"Syria",
    "TRI":"Trieste",
    "TUN":"Tunis",
    "TUS":"Tuscany",
    "TYR":"Tyrolia",
    "TYS":"Tyrrhenian Sea",
    "UKR":"Ukraine",
    "VEN":"Venice",
    "VIE":"Vienna",
    "WAL":"Wales",
    "WAR":"Warsaw",
    "WES":"Western Mediterranean Sea",
    "YOR":"Yorkshire"
}
countries={
    "AUS":"Austria",
    "ENG":"England",
    "FRA":"France",
    "GER":"Germany",
    "ITA":"Italy",
    "RUS":"Russia",
    "TUR":"Turkey"
}
units={
    "AMY":"army",
    "FLT":"fleet"
}
press_orders={
    "ALY":"Ally",
    "AND":"Logical AND",
    "BCC":"Request to Blind Carbon Copy",
    "BWX":"None of Your Business",
    "CCL":"Cancel",
    "CHO":"Choose",
    "DMZ":"Demilitarised Zone",
    "ELS":"IFF Else",
    "EXP":"Explain",
    "FCT":"Fact",
    "FOR":"For specified Turn",
    "FWD":"Request to Forward",
    "HOW":"How to attack",
    "IDK":"I Do Not Know",
    "IFF":"If",
    "INS":"Insist",
    "NAR":"No Agreement",
    "OCC":"Occupy",
    "ORR":"Logical OR",
    "PCE":"Peace",
    "POB":"Position on Board",
    "PRP":"Propose",
    "QRY":"Query",
    "SCD":"Supply Center Distribution",
    "SRY":"Sorry",
    "SUG":"Suggest",
    "THK":"Think",
    "THN":"IFF Then",
    "TRY":"Try the following tokens",
    "UNT":"OCC Unit",
    "VSS":"ALY Versus",
    "WHT":"What to do with",
    "WHY":"Why",
    "XDO":"Moves to do",
    "XOY":"X owes Y",
    "YDO":"You provide the order for",
}